### PR TITLE
Add Magento Enterprise Gift Cards payment line.

### PR DESCRIPTION
**Pull request by jaredkipe**
Unpacks the giftcard code from the PHP serialized information about the giftcards using regex.

-- 
I think that Store Credit, and Rewards should be their own products.  Let me know if you're ok with me adding these products and components.

Additionally, which would you prefer?
component(usage='order.line.builder.rewards')
component(usage='order.line.builder.magento.rewards')
component(usage='magento.order.line.builder.rewards')

### CODE REVIEW

**Comment by jaredkipe** [comment]
I don't see how the travis stuff could have failed for my additions.

**Comment by jaredkipe** [comment]
@guewen Please advise.

**Comment by guewen** [comment]
@jaredkipe I'm terribly sorry, I have been very busy the last weeks. Code LGTM.
I agree component could be nice.

If this is a magento only component, I think it should be 
component(usage='magento.order.line.builder.rewards')
So it respects the implicit convention in this module that all components start with `magento.`. On the other hand, order line builders start with `order.line.builder` so I would be fine with component(usage='order.line.builder.magento.rewards') as well. Sorry if I'm not helpful :)

**Comment by jaredkipe** [comment]
I took my cues from the connector_ecommerce and what you mentioned.  So component name and usage are different just like they are in those modules.

Here is a screen shot from an order that was paid for via all three of the new methods.
screen shot 2017-09-13 at 11 12 28 am

**Comment by guewen** [comment]
Thanks, looks great! I'll try to fix the build of the base PR before merging :)

**Pull request closed without merging**
